/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PersonRouteImport } from './routes/person'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MovieRouteImport } from './routes/movie'
import { Route as IndexRouteImport } from './routes/index'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonRoute = PersonRouteImport.update({
  id: '/person',
  path: '/person',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieRoute = MovieRouteImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie': typeof MovieRoute
  '/movies': typeof MoviesRoute
  '/people': typeof PeopleRoute
  '/person': typeof PersonRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie': typeof MovieRoute
  '/movies': typeof MoviesRoute
  '/people': typeof PeopleRoute
  '/person': typeof PersonRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie': typeof MovieRoute
  '/movies': typeof MoviesRoute
  '/people': typeof PeopleRoute
  '/person': typeof PersonRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie'
    | '/movies'
    | '/people'
    | '/person'
    | '/search'
    | '/tv'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movie' | '/movies' | '/people' | '/person' | '/search' | '/tv'
  id:
    | '__root__'
    | '/'
    | '/movie'
    | '/movies'
    | '/people'
    | '/person'
    | '/search'
    | '/tv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieRoute: typeof MovieRoute
  MoviesRoute: typeof MoviesRoute
  PeopleRoute: typeof PeopleRoute
  PersonRoute: typeof PersonRoute
  SearchRoute: typeof SearchRoute
  TvRoute: typeof TvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person': {
      id: '/person'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof PersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie': {
      id: '/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof MovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieRoute: MovieRoute,
  MoviesRoute: MoviesRoute,
  PeopleRoute: PeopleRoute,
  PersonRoute: PersonRoute,
  SearchRoute: SearchRoute,
  TvRoute: TvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
